apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
    containers:
      - name: my-nginx
        image: nginx:alpine
        livenessProbe:
          httpGet:
            port: 80
            path: /index.html
          initialDelaySeconds: 15
          timeoutSeconds: 2   # defaults to 1
          periodSeconds: 5    # defaults to 10
          failureThreshold: 1 # defaults to 3
        readinessProbe:
          httpGet:
            port: 80
            path: /index.html
          initialDelaySeconds: 3
          timeoutSeconds: 2   # defaults to 1
          periodSeconds: 5    # defaults to 10
          failureThreshold: 1 # defaults to 3
        ports:
          - containerPort: 80
