apiVersion: v1
kind: ConfigMap
metadata:
  name: app-settings
data:
  key1: test 1
  key2: test 2
  key3: test 3
  key4: test 4
  key5: test 5
  key6: test 6
  key7: test 7
  key8: test 8
  key9: test 9
  key10: test 10
  key11: test 11

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-loader
  labels:
    app: env-loader
spec:
  replicas: 1
  template:
    metadata:
      name: env-loader
      labels:
        app: env-loader
    spec:
      containers:
        - name: env-loader
          image: alpine
          command: ["/bin/sh", "-c"]
          args:
            - env
          envFrom:
            - configMapRef:
                name: app-settings
      restartPolicy: Always
  selector:
    matchLabels:
      app: env-loader
