apiVersion: v1
kind: ConfigMap
metadata:
  name: app-settings
data:
  enemies: aliens
  lives: "3"
  enemies.cheat: "true"
  enemies.cheat.level: noGoodRotten

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-loader
  labels:
    app: env-loader
spec:
  replicas: 1
  template:
    metadata:
      name: env-loader
      labels:
        app: env-loader
    spec:
      volumes:
        - name: app-config-vol
          configMap:
            name: app-settings
      containers:
        - name: env-loader
          image: alpine
          command: ["/bin/sh", "-c"]
          args:
            - ls -al /etc/config;echo "environment variable enemies == $(cat /etc/config/enemies)"
          volumeMounts:
            - mountPath: /etc/config
              name: app-config-vol
      restartPolicy: Always
  selector:
    matchLabels:
      app: env-loader
